---
Name: bulkpricing
After: '#catalogueconfig'
---
## Extensions
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\BulkPricing\Extensions\BulkPricingProduct
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\BulkPricing\Extensions\SiteConfigExtension
SilverCommerce\CatalogueAdmin\Import\ProductCSVBulkLoader:
  extensions:
    - SilverCommerce\BulkPricing\Extensions\BulkPricingProductImport